version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    # Allow up to 10 open pull requests for pip dependencies
    open-pull-requests-limit: 10
