"""Make dft_entry_stage_id optional

Revision ID: 35daaf659af4
Revises: 686773cfaa33
Create Date: 2025-10-27 16:53:51.321300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35daaf659af4'
down_revision: Union[str, Sequence[str], None] = '686773cfaa33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pipeline', 'dft_entry_stage_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pipeline', 'dft_entry_stage_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
