"""add is_deleted to company

Revision ID: 56a493827cf0
Revises: 5d51f946e024
Create Date: 2025-11-25 16:57:22.901632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a493827cf0'
down_revision: Union[str, Sequence[str], None] = '5d51f946e024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'is_deleted')
    # ### end Alembic commands ###
