"""Initial schema

Revision ID: 686773cfaa33
Revises:
Create Date: 2025-10-16 17:51:12.746589

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '686773cfaa33'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'admin',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tc2_admin_id', sa.Integer(), nullable=True),
        sa.Column('pd_owner_id', sa.Integer(), nullable=True),
        sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('is_sales_person', sa.Boolean(), nullable=False),
        sa.Column('is_support_person', sa.Boolean(), nullable=False),
        sa.Column('is_bdr_person', sa.Boolean(), nullable=False),
        sa.Column('sells_payg', sa.Boolean(), nullable=False),
        sa.Column('sells_startup', sa.Boolean(), nullable=False),
        sa.Column('sells_enterprise', sa.Boolean(), nullable=False),
        sa.Column('sells_us', sa.Boolean(), nullable=False),
        sa.Column('sells_gb', sa.Boolean(), nullable=False),
        sa.Column('sells_au', sa.Boolean(), nullable=False),
        sa.Column('sells_ca', sa.Boolean(), nullable=False),
        sa.Column('sells_eu', sa.Boolean(), nullable=False),
        sa.Column('sells_row', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_admin_pd_owner_id'), 'admin', ['pd_owner_id'], unique=False)
    op.create_index(op.f('ix_admin_tc2_admin_id'), 'admin', ['tc2_admin_id'], unique=True)
    op.create_table(
        'pipeline',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pd_pipeline_id', sa.Integer(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_pipeline_pd_pipeline_id'), 'pipeline', ['pd_pipeline_id'], unique=True)
    op.create_table(
        'stage',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pd_stage_id', sa.Integer(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_stage_pd_stage_id'), 'stage', ['pd_stage_id'], unique=True)
    op.create_table(
        'company',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('tc2_agency_id', sa.Integer(), nullable=True),
        sa.Column('tc2_cligency_id', sa.Integer(), nullable=True),
        sa.Column('pd_org_id', sa.Integer(), nullable=True),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('price_plan', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('estimated_income', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('utm_campaign', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('utm_source', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('gclid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('signup_questionnaire', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('has_booked_call', sa.Boolean(), nullable=False),
        sa.Column('has_signed_up', sa.Boolean(), nullable=False),
        sa.Column('narc', sa.Boolean(), nullable=False),
        sa.Column('paid_invoice_count', sa.Integer(), nullable=False),
        sa.Column('tc2_status', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=True),
        sa.Column('pay0_dt', sa.DateTime(), nullable=True),
        sa.Column('pay1_dt', sa.DateTime(), nullable=True),
        sa.Column('pay3_dt', sa.DateTime(), nullable=True),
        sa.Column('gclid_expiry_dt', sa.DateTime(), nullable=True),
        sa.Column('email_confirmed_dt', sa.DateTime(), nullable=True),
        sa.Column('card_saved_dt', sa.DateTime(), nullable=True),
        sa.Column('sales_person_id', sa.Integer(), nullable=False),
        sa.Column('support_person_id', sa.Integer(), nullable=True),
        sa.Column('bdr_person_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['bdr_person_id'],
            ['admin.id'],
        ),
        sa.ForeignKeyConstraint(
            ['sales_person_id'],
            ['admin.id'],
        ),
        sa.ForeignKeyConstraint(
            ['support_person_id'],
            ['admin.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_company_pd_org_id'), 'company', ['pd_org_id'], unique=True)
    op.create_index(op.f('ix_company_tc2_agency_id'), 'company', ['tc2_agency_id'], unique=True)
    op.create_index(op.f('ix_company_tc2_cligency_id'), 'company', ['tc2_cligency_id'], unique=True)
    op.create_table(
        'config',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('meeting_dur_mins', sa.Integer(), nullable=False),
        sa.Column('meeting_buffer_mins', sa.Integer(), nullable=False),
        sa.Column('meeting_min_start', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
        sa.Column('meeting_max_end', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
        sa.Column('payg_pipeline_id', sa.Integer(), nullable=True),
        sa.Column('startup_pipeline_id', sa.Integer(), nullable=True),
        sa.Column('enterprise_pipeline_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['enterprise_pipeline_id'],
            ['pipeline.id'],
        ),
        sa.ForeignKeyConstraint(
            ['payg_pipeline_id'],
            ['pipeline.id'],
        ),
        sa.ForeignKeyConstraint(
            ['startup_pipeline_id'],
            ['pipeline.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'contact',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tc2_sr_id', sa.Integer(), nullable=True),
        sa.Column('pd_person_id', sa.Integer(), nullable=True),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['company_id'],
            ['company.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_contact_pd_person_id'), 'contact', ['pd_person_id'], unique=True)
    op.create_index(op.f('ix_contact_tc2_sr_id'), 'contact', ['tc2_sr_id'], unique=True)
    op.create_table(
        'deal',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pd_deal_id', sa.Integer(), nullable=True),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('admin_id', sa.Integer(), nullable=False),
        sa.Column('pipeline_id', sa.Integer(), nullable=False),
        sa.Column('stage_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('contact_id', sa.Integer(), nullable=True),
        sa.Column('support_person_id', sa.Integer(), nullable=True),
        sa.Column('bdr_person_id', sa.Integer(), nullable=True),
        sa.Column('paid_invoice_count', sa.Integer(), nullable=True),
        sa.Column('tc2_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('price_plan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('estimated_income', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('signup_questionnaire', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('utm_campaign', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('utm_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ['admin_id'],
            ['admin.id'],
        ),
        sa.ForeignKeyConstraint(
            ['company_id'],
            ['company.id'],
        ),
        sa.ForeignKeyConstraint(
            ['contact_id'],
            ['contact.id'],
        ),
        sa.ForeignKeyConstraint(
            ['pipeline_id'],
            ['pipeline.id'],
        ),
        sa.ForeignKeyConstraint(
            ['stage_id'],
            ['stage.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_deal_pd_deal_id'), 'deal', ['pd_deal_id'], unique=True)
    op.create_table(
        'meeting',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('start_time', sa.DateTime(), nullable=True),
        sa.Column('end_time', sa.DateTime(), nullable=True),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('meeting_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('admin_id', sa.Integer(), nullable=False),
        sa.Column('contact_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('deal_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['admin_id'],
            ['admin.id'],
        ),
        sa.ForeignKeyConstraint(
            ['company_id'],
            ['company.id'],
        ),
        sa.ForeignKeyConstraint(
            ['contact_id'],
            ['contact.id'],
        ),
        sa.ForeignKeyConstraint(
            ['deal_id'],
            ['deal.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting')
    op.drop_index(op.f('ix_deal_pd_deal_id'), table_name='deal')
    op.drop_table('deal')
    op.drop_index(op.f('ix_contact_tc2_sr_id'), table_name='contact')
    op.drop_index(op.f('ix_contact_pd_person_id'), table_name='contact')
    op.drop_table('contact')
    op.drop_table('config')
    op.drop_index(op.f('ix_company_tc2_cligency_id'), table_name='company')
    op.drop_index(op.f('ix_company_tc2_agency_id'), table_name='company')
    op.drop_index(op.f('ix_company_pd_org_id'), table_name='company')
    op.drop_table('company')
    op.drop_index(op.f('ix_stage_pd_stage_id'), table_name='stage')
    op.drop_table('stage')
    op.drop_index(op.f('ix_pipeline_pd_pipeline_id'), table_name='pipeline')
    op.drop_table('pipeline')
    op.drop_index(op.f('ix_admin_tc2_admin_id'), table_name='admin')
    op.drop_index(op.f('ix_admin_pd_owner_id'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
